export * from "./common.interface";
export * from "./config.interface";
export * from "./otp.interface";
export * from "./role.interface";
export * from "./router.interface";
export * from "./user-address.interface";
export * from "./user-auth.interface";
export * from "./user-profile.interface";
export * from "./user.interface";